####################################################################################################################################
# Configuration #                                                                                                                  #
####################################################################################################################################

### NOTES ###
# [Section] tags MUST be at the far left; no spaces allowed before the tag starts, else ViewINI will not see that secion.

### TODO ###
# - Add Additional Options
# - Ensure excludes files moved to excludes folder are called correctly.

#-------------------------#
# Excludes  #
# ------------------------#

[Excludes]
  FilePath="excludes" # NOIMPL
  FileName="excludes.list"
  Variable="FilteredExcludes_FileName"

[Filtered_Excludes]
  FilePath="excludes" # NOIMPL
  FileName="excludes-filtered.list"
  Variable="FilteredExcludes_FileName"


