####################################################################################################################################
# Configuration #                                                                                                                  #
####################################################################################################################################

### NOTES ###
# [Section] tags MUST be at the far left; no spaces allowed before the tag starts, else ViewINI will not see that secion.

### TODO ###
# - Add Additional Options


#-------------------------#
# Legacy Reposync Feature #
# ------------------------#

#   DISABLED: dnf reposync = DNF 5
#   ENABLED:  reposync     = DNF 4

[Legacy_RepoSync]
  Name="Legacy Reposync"
  Description="Not Yet"
  Variable="Legacy_Reposync"
  Enabled="0"

