####################################################################################################################################
# Configuration #                                                                                                                  #
####################################################################################################################################

### NOTES ###
# [Section] tags MUST be at the far left; no spaces allowed before the tag starts, else ViewINI will not see that secion.

### TODO ###
# - Add Additional Options


#-------------------------#
# Program Options         #
# ------------------------#
# Options here are not parameters for Reposync; they are options for this utility.

[Config_Clean-Metadata]
  Name="Clean Metadata"
  Description="Not Yet"
  Variable="Cfg_CLEAN_METADATA"
  Enabled="0"


[Config_Remove-Filtered-File]
  Name="Remove Filtered File"
  Description="Not Yet"
  Variable="Cfg_REMOVE_FILTERED_FILE"
  Enabled="0"

