####################################################################################################################################
# Configuration #                                                                                                                  #
####################################################################################################################################

#-------------------------#
# Legacy Reposync Feature #
# ------------------------#

#       dnf reposync = DNF 5
#       reposync     = DNF 4
  Legacy_RepoSync_Enabled="0"


#----------------------------------------------#
# Reposync Options - PENDING DEPRICATION       #
# ---------------------------------------------#
  
#   prog="dnf reposync" # Can be either 'reposync' or dnf reposync'
#   args=" -n -m --delete"
#   debug=" --debug" # use this to debug reposync when there are issues.



#-----------------------------------#
# Reposync Options - TESTING        #
# ----------------------------------#
# This section will supercede the Reposync Options section once implemented.
# TODO: Enable ability to use 0/1, Y/N, y/n, True/False (convert to uppercase before processing on run)

  Cfg_KEEP_NEWEST_ONLY="0"
  Cfg_DOWNLOAD_METADATA="0"
  Cfg_DELETE_ENABLED="0"
  Cfg_DEBUG_ENABLED="0"

# Options here are not parameters for Reposync; they are options for this utility.
  Cfg_CLEAN_METADATA="0"
  Cfg_REMOVE_FILTERED_FILE="0"

#-------------------------#
# Excludes Feature        #
# ------------------------#

# Excludes Feature #
# excludes="*debug*,*-langpack-*,*-source-*,*-src-*,*-headless-*,*-langpack-*,libreoffice-help-*"
  Repo_Excludes="$(cat excludes-filtered.list)" # Initial value to prevent file not found error.

#  RepoID="fedora"
# Initialize blank $RepoID for use in CASE statement later 
  RepoID=""

#-------------------------#
# File Filtering Feature  #
# ------------------------#

  Excludes_FilePath="$(pwd)"
  Excludes_FileName="excludes.list"
  FilteredExcludes_FileName="excludes-filtered.list"

