####################################################################################################################################
# Configuration #                                                                                                                  #
####################################################################################################################################

#-------------------------#
# Legacy Reposync Feature #
# ------------------------#

#       dnf reposync = DNF 5
#       reposync     = DNF 4
 [Legacy_RepoSync]
  Name='Legacy Reposync'
  Description=None
  Variable=Legacy_Reposync
  Enabled=0



#-----------------------------------#
# Reposync Options                  #
# ----------------------------------#
# This section will supercede the Reposync Options section once implemented.
# TODO: Enable ability to use 0/1, Y/N, y/n, True/False (convert to uppercase before processing on run)
 [Reposync_Keep-Newest-Only]
  Name='Keep Only Newest Packages'
  Description=None
  Variable=Cfg_KEEP_NEWEST_ONLY
  Enabled=0

 [Reposync_Download-Metadata]
  Name='Download Metadata'
  Description=None
  Variable=Cfg_DOWNLOAD_METADATA
  Enabled=0

 [Reposync_Delete-Old-Packages]
  Name='Delete Old Packages'
  Description=None
  Variable=Cfg_DELETE_ENABLED
  Enabled=0


 [Reposync_Debugging]
  Name='Debugging'
  Description=None
  Variable=Cfg_DEBUG_ENABLED
  Enabled=0


# Options here are not parameters for Reposync; they are options for this utility.
 [Config_Clean-Metadata]
  Name='Clean Metadata'
  Description=None
  Variable=Cfg_CLEAN_METADATA
  Enabled=0


 [Config_Remove-Filtered-File]
  Name='Remove Filtered File'
  Description=None
  Variable=Cfg_REMOVE_FILTERED_FILE
  Enabled=0



#############################################################################################################################################

#-------------------------#
# File Filtering Feature  #
# ------------------------#
 [Excludes]
#  FilePath= # NOIMPL
  FileName=excludes.list
  Variable=FilteredExcludes_FileName

 [Filtered_Excludes]
#  FilePath= # NOIMPL
  FileName=excludes-filtered.list
  Variable=FilteredExcludes_FileName

