####################################################################################################################################
# Configuration #                                                                                                                  #
####################################################################################################################################

### NOTES ###
# [Section] tags MUST be at the far left; no spaces allowed before the tag starts, else ViewINI will not see that secion.
#
### TODO ###
# - Add Additional Options

#-------------------------#
# Legacy Reposync Feature #
# ------------------------#

#   DISABLED: dnf reposync = DNF 5
#   ENABLED:  reposync     = DNF 4

[Legacy_RepoSync]
  Name="Legacy Reposync"
  Description="Not Yet"
  Variable="Legacy_Reposync"
  Enabled="0"

#-------------------------#
# Program Options         #
# ------------------------#
# Options here are not parameters for Reposync; they are options for this utility.

[Config_Clean-Metadata]
  Name="Clean Metadata"
  Description="Not Yet"
  Variable="Cfg_CLEAN_METADATA"
  Enabled="0"


[Config_Remove-Filtered-File]
  Name="Remove Filtered File"
  Description="Not Yet"
  Variable="Cfg_REMOVE_FILTERED_FILE"
  Enabled="0"


#-----------------------------------#
# Reposync Options                  #
# ----------------------------------#
# This section will supercede the Reposync Options section once implemented.
# TODO: Enable ability to use 0/1, Y/N, y/n, True/False (convert to uppercase before processing on run)
  
[Reposync_Keep-Newest-Only]
  Name="Keep Only Newest Packages"
  Description="None Yet"
  Variable="Cfg_KEEP_NEWEST_ONLY"
  Enabled="0"

[Reposync_Download-Metadata]
  Name="Download Metadata"
  Description="Not Yet"
  Variable="Cfg_DOWNLOAD_METADATA"
  Enabled="0"

[Reposync_Delete-Old-Packages]
  Name="Delete Old Packages"
  Description="Not Yet"
  Variable="Cfg_DELETE_ENABLED"
  Enabled="0"


[Reposync_Debugging]
  Name="Debugging"
  Description="Not Yet"
  Variable="Cfg_DEBUG_ENABLED"
  Enabled="0"



#############################################################################################################################################

#-------------------------#
# File Filtering Feature  #
# ------------------------#
[Excludes]
#  FilePath="" # NOIMPL
  FileName="excludes.list"
  Variable="FilteredExcludes_FileName"

[Filtered_Excludes]
#  FilePath="" # NOIMPL
  FileName="excludes-filtered.list"
  Variable="FilteredExcludes_FileName"

